### ISSUE TITLE
隐私信息删除

### ISSUE THREAD

**Issue by tzwm** [soulteary/Get-D2-2014-Ticket#850]
这 repo 可以删除吗，应该已经过期了吧？涉及到很多人的隐私信息，在 Google 上都能直接搜到。

**Comment by hax** [comment]
删除也没什么卵用，有很多fork啊。

**Comment by tzwm** [comment]
因为这个 repo 在 google 上权值比较高，至少能一定程度上减少曝光。

**Comment by soulteary** [comment]
@tzwm 哈哈，我搜索了一下，还真是，不过G的相关结果有16w，估计是删除不掉了，如果你十分care，大概需要去找各种fork和私仓作者提交pr了。

讲真删除意义不大，public/private repo一堆，最多的时候记得有800+

如果你十分care你提交的文件，可以参考他 https://github.com/soulteary/Get-D2-2014-Ticket/pull/848/files ，虽然其实和做这个事情没差别 https://github.com/search?q=remove+password&type=Commits&utf8=%E2%9C%93 ...但是至少可以在某种程度上减少个人信息的曝光。

----

没想到 @hax 贺老也来了，我觉得可以考虑把ticket dir rebase干掉，留下演讲的link，不过一堆私仓／fork没法移除。
